name: astralis-agency
region: sfo
services:
  - name: api
    github:
      repo: your-github-username/astralis-agency
      branch: main
      deploy_on_push: true
    build_command: cd server && yarn install && yarn build
    run_command: >
      cd server &&
      yarn setup:db &&
      yarn seed:db &&
      yarn start:prod
    envs:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3001"
      - key: DB_HOST
        scope: RUN_TIME
        value: ${db.HOSTNAME}
      - key: DB_PORT
        scope: RUN_TIME
        value: ${db.PORT}
      - key: DB_USER
        scope: RUN_TIME
        value: ${db.USERNAME}
      - key: DB_PASSWORD
        scope: RUN_TIME
        value: ${db.PASSWORD}
      - key: DB_NAME
        scope: RUN_TIME
        value: ${db.DATABASE}
    http_port: 3001
    instance_count: 1
    instance_size_slug: basic-xxs
    health_check:
      http_path: /api/health
      initial_delay_seconds: 30
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3

databases:
  - engine: PG
    name: db
    num_nodes: 1
    size: db-s-dev-database
    version: "14" 