version: '3.8'

services:
  app:
    build: .
    container_name: astralis-agency-server
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      NODE_ENV: production
      DATABASE_URL: postgres://postgres:password@db:5432/astralis
    volumes:
      - .:/app
      - /app/node_modules
    command: ["yarn", "start:prod"]

  db:
    image: postgres:15-alpine
    container_name: postgres-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: astralis
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
