AWSTemplateFormatVersion: '2010-09-09'
Description: AWS SAM CLI Nested Stack for Auto Dependency Layer Creation
Metadata:
  SamCliInfo: 1.132.0
  key: AWS SAM CLI sync command
Outputs:
  contactFormHandler2528f845DepLayer:
    Value:
      Ref: contactFormHandler2528f845DepLayer
Resources:
  contactFormHandler2528f845DepLayer:
    Metadata:
      CreatedBy: AWS SAM CLI sync command
    Properties:
      CompatibleRuntimes:
      - nodejs22.x
      ContentUri: /Users/gregstarr/projects/dev/AstralisAgency/aws/.aws-sam/auto-dependency-layer/contactFormHandler2528f845DepLayer
      Description: Auto created layer for dependencies of function contactFormHandler
      LayerName: contact-form-han33c50d57-contactFormHandler2528f845-DepLayer
      RetentionPolicy: Delete
    Type: AWS::Serverless::LayerVersion
Transform: AWS::Serverless-2016-10-31
